version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 nexus:
  build: ./docker-nexus3 
  restart: always
  ports:
    - "18081:8081"
  networks:
    - prodnetwork
  volumes:
    - /opt/sonatype/nexus:/nexus-data 

 jenkins:
  build: ./jenkins
  restart: always
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /opt/jenkins/:/var/lib/jenkins/
  depends_on:
    - nexus
    - gitlab
    - sonar
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonardb:
  networks:
    - prodnetwork
  restart: always
  image: postgres:9.6
  ports:
    - "5432:5432" 
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

 sonar:
  image: sonarqube 
  restart: always
  ports:
   - "39000:9000"
   - "39092:9092"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar

 gitlab:
  image: gitlab/gitlab-ce:latest
  restart: always
  networks:
    - prodnetwork
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      # external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - "580:80"
    - "5443:443"
    - "522:22"
  volumes:
    - /opt/gitlab/config:/etc/gitlab
    - /opt/gitlab/logs:/var/log/gitlab
    - /opt/gitlab/data:/var/opt/gitlab

 jboss:
  build: ./jboss
  restart: always
  ports:
    - "28080:8080"
    - "9090:9090"
    - "8787:8787"
  networks:
    - prodnetwork
  volumes:
    - /opt/jboss:/var/log/jboss